import Head from 'next/head'
import Link from 'next/link'
import { Card, CardContent, CardDescription, CardTitle } from '@ui/card'
import BaseLayout from '@/components/layout/BaseLayout'
import { type ReactElement } from 'react'
import { type NextPageWithLayout } from './_app'

const Home: NextPageWithLayout = () => {
  return (
    <>
      <Head>
        <title>Quizzr</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-1 place-items-stretch gap-x-8 gap-y-16 px-32 pb-8 lg:grid-flow-dense lg:grid-cols-2">
        <Card className="mt-8 flex flex-col gap-8 p-16 lg:col-span-2">
          <CardTitle className="font-cursive w-full text-center text-8xl">
            Welcome to Quizzr
          </CardTitle>
          <CardContent className="flex flex-col gap-8">
            <h3 className="w-full text-center text-2xl italic">
              <span className="font-bold italic">WIP</span>, but it&apos;s online for the lulz
            </h3>
            <Link
              href="/app"
              className="max-w-xs self-center rounded-md bg-accent px-8 py-4 text-xl"
            >
              Open the App
            </Link>
          </CardContent>
        </Card>
        <div className="min-h-32 col-start-1 flex h-full min-h-[16rem] w-full items-center justify-center bg-teal-900 lg:col-start-2">
          <h4 className="text-xl">Image here </h4>
        </div>
        <Card className="col-start-1 ">
          <CardTitle className="w-full text-center text-3xl">What even is this?</CardTitle>
          <CardContent className="flex flex-col gap-4">
            <p>Long story short, it&apos;s an app to help you study</p>
            <p>Long story a bit longer:</p>
            <ul className="flex list-disc flex-col gap-1 px-4">
              <li>Create multiple choice quizzes or flashcards!</li>
              <li>Set number of repeats of each question!</li>
              <li>
                Learn by repetition, each question will appear until you remember the answer a few
                times!
              </li>
              <li>Share your question sets with friends!</li>
              <li>Edit sets together!</li>
              <li>Share feedback with the quizz author!</li>
            </ul>
          </CardContent>
        </Card>

        <div className="col-start-1 flex h-full min-h-[16rem]  w-full items-center justify-center bg-teal-900">
          <h4 className="text-xl">Image here </h4>
        </div>
        <Card className="col-start-1 lg:col-start-2 ">
          <CardTitle className="w-full text-center text-3xl">
            That&apos;s neat, but I&apos;ve got books
          </CardTitle>
          <CardContent className="flex flex-col gap-4">
            <p>
              Good for you! But books/notes are pretty boring, and you usually read them once or
              twice, and in the same order every time.
            </p>
            <p>
              Here you always get different questions, with differently ordered answers, in random
              order!
            </p>
            <p>This helps you actually learn information, not just words</p>
          </CardContent>
        </Card>
        <div className="min-h-32 col-start-1 flex h-full min-h-[16rem] w-full items-center justify-center bg-teal-900 lg:col-start-2">
          <h4 className="text-xl">Image here </h4>
        </div>
        <Card className="col-start-1">
          <CardTitle className="w-full text-center text-3xl">
            But it takes a while to put everything into a question set
          </CardTitle>
          <CardContent className="flex flex-col gap-4">
            <p>Sure, that&apos;s a good point. But you don&apos;t have to do it alone!</p>
            <p>If your friends also study the same topics, you can collaborate!</p>
            <p>
              In a set of 40 questions, with 8 people you only need to make 5 questions each.
              Doesn&apos;t seem too bad.
            </p>
            <p>
              And if you&apos;re feeling technical, there will (later) be import from a txt file,
              you can all write questions in any synchronised document, save it as a .txt and put
              everything in the app! <br /> This doens&apos;t include any extra functionality like
              images of course, but it&apos;s a good method to get something up quickly
            </p>
          </CardContent>
        </Card>
      </div>
    </>
  )
}

Home.getLayout = function getLayout(page: ReactElement) {
  return <BaseLayout>{page}</BaseLayout>
}

export default Home
